recruiter/urls.py
from django.urls import path
from .views import *

app_name = 'recruiter'

urlpatterns = [
    path('create/', RecruiterCreateView.as_view(), name='create'),
    path('list/', RecruiterListView.as_view(), name='list'),
    path('detail/<slug:slug>/', RecruiterDetailView.as_view(), name='detail'),
    path('update/<slug:slug>/', RecruiterUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', RecruiterDeleteView.as_view(), name='delete'),
]

registration_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('referral/', include('referral.urls', namespace='referral')),
    path('recruiter/', include('recruiter.urls', namespace='recruiter')),
    path('user/', include('user.urls')),
    path('', include('home_page.urls', namespace='home')),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

recruiter/models.py
from django.db import models
from django.urls import reverse
from django.utils.datetime_safe import datetime


class Recruiter(models.Model):
    last_name = models.CharField(max_length=50, db_index=True)
    first_name = models.CharField(max_length=50, db_index=True)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    passport_id = models.CharField(max_length=9, db_index=True, unique=True)
    slug = models.SlugField(max_length=14, unique=True)
    area = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    village = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=50)
    birthday = models.DateField(default=datetime.now)
    created = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return '{} {} {}'.format(self.last_name, self.first_name, self.middle_name)

    def get_absolute_url(self):
        return reverse('recruiter:detail', args=[self.slug])

recruiter/forms.py
from django import forms
from django.utils.datetime_safe import datetime

from .models import Recruiter


class RecruiterCreateForm(forms.ModelForm):
    last_name = forms.CharField(label='Фамилия')
    first_name = forms.CharField(label='Имя')
    middle_name = forms.CharField(label='Отчество')
    passport_id = forms.CharField(label='ID паспорта', max_length=9)
    slug = forms.IntegerField(label='Персональный номер', widget=forms.TextInput(attrs={
        'maxlength': '14'
    }), error_messages={'invalid': 'Введен неправильный номер'})
    area = forms.CharField(max_length=50)
    region = forms.CharField(label='Район')
    village = forms.CharField(label='Село', required=False)
    address = forms.CharField(label='Адрес')
    birthday = forms.DateField(label='Дата рождения', initial=datetime.now(), help_text='Формат даты, ДД/ММ/ГГГГ')

    class Meta:
        model = Recruiter
        exclude = ('created',)
        fields = '__all__'

recruiter/views.py
from django.views.generic import CreateView, TemplateView, ListView, DetailView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Recruiter
from .forms import RecruiterCreateForm


class RecruiterListView(LoginRequiredMixin, ListView):
    model = Recruiter
    template_name = 'list_of_recruiter.html'
    paginate_by = 3
    context_object_name = 'recruiters'
    ordering = ('last_name', 'first_name', 'middle_name',)


class RecruiterDetailView(LoginRequiredMixin, DetailView):
    model = Recruiter
    template_name = 'detail_of_recruiter.html'
    slug_field = 'slug'


class RecruiterCreateView(LoginRequiredMixin, CreateView):
    model = Recruiter
    form_class = RecruiterCreateForm
    template_name = 'create_of_recruiter.html'
    slug_field = 'slug'


class RecruiterUpdateView(LoginRequiredMixin, UpdateView):
    model = Recruiter
    form_class = RecruiterCreateForm
    template_name = 'update_of_recruiter.html'
    slug_field = 'slug'


class RecruiterDeleteView(LoginRequiredMixin, DeleteView):
    model = Recruiter
    template_name = 'delete_of_recruiter.html'
    success_url = reverse_lazy('recruiter:list')
    slug_field = 'slug'

recruiter/templates/create_of_recruiter.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Создать рекрутера
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="page-header">
            <h3>Создать рекрутера</h3>
            <a type="button" class="btn btn-primary" href="{% url 'recruiter:list' %}">К списку</a>
        </div>
        <div class="custom-form">
            <form action="" method="post">{% csrf_token %}

                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.middle_name|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.passport_id|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.slug|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.area|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.region|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.village|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.address|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.birthday|as_crispy_field }}
                    </div>
                </div>

                <button class="btn btn-primary" type="submit">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock %}

recruiter/templates/delete_of_recruiter.html
{% extends 'base.html' %}

{% block title %}
    Удалить рекрутера
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="page-header">
            <h1>Удалить рекрутера?</h1>
        </div>
        <form action="" method="post">{% csrf_token %}
            <p>Вы уверены что хотите удалить <a href="{% url 'recruiter:detail' object.slug %}">"{{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}</a>"?</p>
            <p>При его удалении будут удалены все его рефералы и их информация!</p>
            <button class="btn btn-danger" type="submit">Удалить</button>
            <a href="{% url 'recruiter:detail' object.slug %}" class="btn btn-secondary ">Нет</a>
        </form>
    </div>
{% endblock %}

recruiter/templates/detail_of_recruiter.html
{% extends 'base.html' %}

{% block title %}
    {{ object.last_name }} {{ object.first_name }}
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="page-header">
            <h3>Рекрутер</h3>
            <a type="button" class="btn btn-primary" href="{% url 'recruiter:create' %}">Создать рекрутера</a>
        </div>
        <div class="page-header">
            <h4> {{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}</h4>
            <a type="button" class="btn btn-primary" href="{% url 'recruiter:list' %}">К списку</a>
        </div>

        <div class="row">
            <div class="col-6">
                <ul class="list-group-flush custom-list-group">
                    <li class="list-group-item active">ФИО: </li>
                    <li class="list-group-item"><span class="list-group-name">Фамилия:</span>{{ object.last_name }}</li>
                    <li class="list-group-item"><span class="list-group-name">Имя:</span>{{ object.first_name }}</li>
                    <li class="list-group-item"><span class="list-group-name">Отчество:</span>{{ object.middle_name }}</li>
                </ul>
                <ul class="list-group-flush custom-list-group">
                    <li class="list-group-item active"> Паспортные данные: </li>
                    <li class="list-group-item"><span class="list-group-name">ID паспорта:</span>{{ object.passport_id }}</li>
                    <li class="list-group-item"><span class="list-group-name">Персональный номер:</span>{{ object.slug }}</li>
                </ul>
                <ul class="list-group-flush custom-list-group">
                    <li class="list-group-item active">Место прописки: </li>
                    <li class="list-group-item"><span class="list-group-name">Город/Область:</span>{{ object.area }}</li>
                    <li class="list-group-item"><span class="list-group-name">Район:</span>{{ object.region }}</li>
                    {% if object.village %}
                        <li  class="list-group-item"><span class="list-group-name">Село:</span>{{ object.village }}</li>
                    {% endif %}
                    <li class="list-group-item"><span class="list-group-name">Адрес:</span>{{ object.address }}</li>
                </ul>
                <a type="button" class="btn btn-primary" href="{% url 'recruiter:update' object.slug %}">Изменить</a>
                <a type="button" class="btn btn-primary" href="{% url 'recruiter:delete' object.slug %}">Удалить</a>
            </div>

            <div class="col-6">
                <ul class="list-group-flush custom-list-group ">
                    <li class="list-group-item active">Список его рефералов</li>
                    {% for referral in object.recruiter.all %}
                        <li class="list-group-item">
                            <a href="{% url 'referral:detail' referral.slug %}">{{ referral.last_name }} {{ referral.first_name }} {{ referral.middle_name }}</a>
                        </li>
                    {% endfor %}
                    <li class="list-group-item">
                    <li class="list-group-item active"><a class="list-group-item active" href="{% url 'referral:create' %}">Добавить рефералов</a></li>
                    </li>
                </ul>
            </div>
        </div>



    </div>
{% endblock %}

recruiter/templates/list_of_recruiter.html
{% extends 'base.html' %}
{% block title %}
    Список рекрутеров
{% endblock %}
{% block content %}
    <div class="page-container">
        <div class="page-header">
            <h3>Рекрутеры</h3>
            <a type="button" class="btn btn-primary" href="{% url 'recruiter:create' %}">Создать рекрутера</a>
        </div>

        <ul class="list-group">
            {% for recruiter in recruiters %}
                <li class="list-group-item"><a href="{% url 'recruiter:detail' recruiter.slug %}">{{ recruiter.last_name }} {{ recruiter.first_name }} {{ recruiter.middle_name }}</a></li>
            {% endfor %}
        </ul>

        <!---------------------  PAGINATION --------------------->
        {% if is_paginated %}
            <nav>
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="/recruiter/list/?page={{ page_obj.previous_page_number }}"> < </a>
                        </li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active">
                                <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="/recruiter/list/?page={{ page_obj.next_page_number }}"> > </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
{% endblock %}

recruiter/templates/update_of_recruiter.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Изменить рекрутера
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="page-header">
            <h3>Изменить рекрутера</h3>
            <a type="button" class="btn btn-primary" href="{% url 'recruiter:detail' object.slug %}">Назад</a>
        </div>
        <div class="custom-form">
            <form action="" method="post">{% csrf_token %}

                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.middle_name|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.passport_id|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.slug|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.area|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.region|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.village|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.address|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.birthday|as_crispy_field }}
                    </div>
                </div>

                <button class="btn btn-primary" type="submit">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock %}