referral/urls.py
from django.urls import path
from .views import *

app_name = 'referral'

urlpatterns = [
    path('create/', ReferralCreateView.as_view(), name='create'),
    path('list/', ReferralListView.as_view(), name='list'),
    path('detail/<slug:slug>/', ReferralDetailView.as_view(), name='detail'),
    path('update/<slug:slug>/', ReferralUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', ReferralDeleteView.as_view(), name='delete'),
    path('filter/<int:pk>', ReferralListView.referral_filter, name="filter"),

    # path('area/', ReferralArea.as_view(), name='area')
]

registration_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('referral/', include('referral.urls', namespace='referral')),
    path('recruiter/', include('recruiter.urls', namespace='recruiter')),
    path('user/', include('user.urls')),
    path('', include('home_page.urls', namespace='home')),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

referral/models.py
from django.db import models
from django.urls import reverse
from django.utils.datetime_safe import datetime

from recruiter.models import Recruiter

STATUS_CHOICES = (
    ('Нет совпадений', 'Нет совпадений'), ('Есть совпадения', 'Есть совпадения'),
)


class Referral(models.Model):
    last_name = models.CharField(max_length=50, db_index=True)
    first_name = models.CharField(max_length=50, db_index=True)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    passport_id = models.CharField(max_length=9, db_index=True, unique=True)
    slug = models.SlugField(max_length=14, unique=True)
    area = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    village = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=50)
    birthday = models.DateField(default=datetime.now)
    recruiter = models.ForeignKey(Recruiter, on_delete=models.CASCADE,  verbose_name='Рекрутер', related_name='recruiter')
    status = models.CharField(choices=STATUS_CHOICES, max_length=20, default='Нет совпадений')
    created = models.DateTimeField(default=datetime.now)

    def get_absolute_url(self):
        return reverse('referral:detail', args=[self.slug])

referral/forms.py
from django import forms
from django.utils.datetime_safe import datetime

from .models import Referral, STATUS_CHOICES


class ReferralCreateForm(forms.ModelForm):
    last_name = forms.CharField(label='Фамилия')
    first_name = forms.CharField(label='Имя')
    middle_name = forms.CharField(label='Отчество')
    passport_id = forms.CharField(label='ID паспорта', max_length=9)
    slug = forms.IntegerField(label='Персональный номер', widget=forms.TextInput(attrs={
        'maxlength': '14'
    }), error_messages={'invalid': 'Введен неправильный номер'})
    area = forms.CharField(label='Город, область')
    region = forms.CharField(label='Район')
    village = forms.CharField(label='Село', required=False)
    address = forms.CharField(label='Адрес')
    recruiter = forms.Select()
    birthday = forms.DateField(label='Дата рождения', initial=datetime.now(), help_text='Формат даты, ДД/ММ/ГГГГ')
    status = forms.ChoiceField(choices=STATUS_CHOICES, label='Статус')

    class Meta:
        model = Referral
        fields = '__all__'
        exclude = ('created', )

referral/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.views.generic import CreateView, TemplateView, ListView, DetailView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (LoginRequiredMixin)
from .models import Referral
from .forms import ReferralCreateForm


class ReferralListView(LoginRequiredMixin, ListView):
    model = Referral
    template_name = 'list_of_referrals.html'
    paginate_by = 3
    context_object_name = 'referrals'
    ordering = ('last_name', 'first_name', 'middle_name', )

    def referral_filter(request, pk):
        referral = Referral.objects.all()
        paginator = Paginator(referral, 3)
        if pk == 1:
            referral = referral.order_by('last_name', 'first_name', 'middle_name', )
        elif pk == 2:
            referral = referral.order_by('-created', )
        elif pk == 3:
            referral = referral.order_by('recruiter__last_name', 'recruiter__first_name', 'recruiter__middle_name')
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, "list_of_referrals.html", {"referrals": referral, 'page_obj': page_obj})


class ReferralDetailView(LoginRequiredMixin, DetailView):
    model = Referral
    template_name = 'detail_of_referrals.html'


class ReferralCreateView(LoginRequiredMixin, CreateView):
    model = Referral
    form_class = ReferralCreateForm
    template_name = 'create_of_referrals.html'


class ReferralUpdateView(LoginRequiredMixin, UpdateView):
    model = Referral
    form_class = ReferralCreateForm
    template_name = 'update_of_referrals.html'


class ReferralDeleteView(LoginRequiredMixin, DeleteView):
    model = Referral
    template_name = 'delete_of_referrals.html'
    success_url = reverse_lazy('referral:list')


class ReferralArea(ListView):
    model = Referral
    template_name = 'regions/area.html'
    context_object_name = 'areas'


# def referral_filter(request, pk):
#     """ Фильтр статей по дате
#     """
#     referral = Referral.objects.all()
#     if pk == 1:
#         referral = referral.order_by('last_name', 'first_name', 'middle_name', )
#     elif pk == 2:
#         referral = referral.order_by('created', )
#
#     return render(request, "list_of_referrals.html", {"referrals": referral})

referral/templates/create_of_referrals.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Создать реферала
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="page-header">
            <h3>Создать реферала</h3>
            <a type="button" class="btn btn-primary" href="{% url 'referral:list' %}">К списку</a>
        </div>
        <div class="custom-form">
            <form action="" method="post">{% csrf_token %}

                <br>

                {{ form.recruiter|as_crispy_field }}

                <br>

                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.middle_name|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.passport_id|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.slug|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.area|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.region|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.village|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.address|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.birthday|as_crispy_field }}
                    </div>

                    <div class="form-group col-md-6 mb-0">
                        {{ form.status|as_crispy_field }}
                    </div>
                </div>

                <button class="btn btn-primary" type="submit">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock %}

referral/templates/delete_of_referrals.html
{% extends 'base.html' %}

{% block title %}
    Удалить реферала
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="page-header">
            <h1>Удалить реферала?</h1>
        </div>
        <div class="custom-form">
            <form action="" method="post">{% csrf_token %}
                <p>Вы уверены что хотите удалить "{{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}"?</p>
                <button class="btn btn-danger" type="submit">Удалить</button>
                <a href="{% url 'referral:detail' object.slug %}" class="btn btn-secondary">Нет</a>
            </form>
        </div>
    </div>
{% endblock %}

referral/templates/detail_of_referrals.html
{% extends 'base.html' %}

{% block title %}
    {{ object.last_name }} {{ object.first_name }}
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="page-header">
            <h3>Реферал</h3>
            <a type="button" class="btn btn-primary" href="{% url 'referral:create' %}">Создать реферала</a>
        </div>
        <div class="page-header">
            <h4> {{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}</h4>
            <a type="button" class="btn btn-primary" href="{% url 'referral:list' %}">К списку</a>
        </div>

        <div class="row">
            <div class="col-6">
                <ul class="list-group-flush custom-list-group">
                    <li class="list-group-item active">ФИО: </li>
                    <li class="list-group-item"><span class="list-group-name">Фамилия:</span>{{ object.last_name }}</li>
                    <li class="list-group-item"><span class="list-group-name">Имя:</span>{{ object.first_name }}</li>
                    <li class="list-group-item"><span class="list-group-name">Отчество:</span>{{ object.middle_name }}</li>
                </ul>


                <ul class="list-group-flush custom-list-group">
                    <li class="list-group-item active"> Паспортные данные: </li>
                    <li class="list-group-item"><span class="list-group-name">ID паспорта:</span>{{ object.passport_id }}</li>
                    <li class="list-group-item"><span class="list-group-name">Персональный номер:</span>{{ object.slug }}</li>
                </ul>

                <ul class="list-group-flush custom-list-group">
                    <li class="list-group-item active">Место прописки: </li>
                    <li class="list-group-item"><span class="list-group-name">Город/Область:</span>{{ object.area }}</li>
                    <li class="list-group-item"><span class="list-group-name">Район:</span>{{ object.region }}</li>
                    {% if object.village %}
                        <li  class="list-group-item"><span class="list-group-name">Село:</span>{{ object.village }}</li>
                    {% endif %}
                    <li class="list-group-item"><span class="list-group-name">Адрес:</span>{{ object.address }}</li>
                </ul>

                <a type="button" class="btn btn-primary" href="{% url 'referral:update' object.slug %}">Изменить</a>
                <a type="button" class="btn btn-primary" href="{% url 'referral:delete' object.slug %}">Удалить</a>
            </div>

            <div class="col-6">
                <ul class="list-group-flush custom-list-group">
                    <li class="list-group-item active">Список его рекрутеров:</li>
                    <li class="list-group-item"><span class="list-group-name"></span><a href="{% url 'recruiter:detail' object.recruiter.slug %}">
                        {{ object.recruiter.last_name}} {{ object.recruiter.first_name }} {{ object.recruiter.middle_name }}</a></li>
                </ul>

                <ul class="list-group-flush custom-list-group">
                    <li class="list-group-item active">Статус:</li>
                    <li class="list-group-item"><span class="list-group-name"></span>{{ object.status.title }}</li>
                </ul>
            </div>
            {#        <div class="col-6">#}
            {##}
            {#        </div>#}
        </div>
    </div>
{% endblock %}

referral/templates/list_of_referrals.html
{% extends 'base.html' %}
{% block title %}
    Список рефералов
{% endblock %}
{% block content %}
    <div class="page-container">

        <div class="page-header">
            <h3>Рефералы</h3>
            <a type="button" class="btn btn-primary" href="{% url 'referral:create' %}">Создать реферала</a>
        </div>

        <div class="page-header">
            <h5>Сортировка по:</h5>
        </div>

        <div>
            <a type="button" class="btn btn-primary" href="{% url 'referral:filter' pk=1 %}">алфавиту</a>
            <a type="button" class="btn btn-primary" href="{% url 'referral:filter' pk=2 %}">дате регистрации</a>
            <a type="button" class="btn btn-primary" href="{% url 'referral:filter' pk=3 %}">рекрутеру</a>
            <a type="button" class="btn btn-primary" href="{% url 'referral:list' %}">Все</a>
        </div>

        <br>


        <div class="row">
            <div class="col-12">
                <ul class="list-group list-group-horizontal-md">
                    <li class="list-group-item col-5" style="background: #007fff">ФИО</li>
                    <li class="list-group-item col-5" style="background: #007fff">Рекрутер</li>
                    <li class="list-group-item col-2" style="background: #007fff">Зарегистрирован</li>
                </ul>
            </div>
            <div class="col-12">
                {% for referral in referrals %}
                    <ul class="list-group list-group-horizontal-md">
                        <li class="list-group-item col-5"><a href="{% url 'referral:detail' referral.slug %}">{{ referral.last_name }} {{ referral.first_name }} {{ referral.middle_name }}</a></li>
                        <li class="list-group-item col-5">{{ referral.recruiter.last_name }} {{ referral.recruiter.first_name }} {{ referral.recruiter.middle_name }}</li>
                        <li class="list-group-item col-2">{{ referral.created.date }}</li>
                    </ul>
                {% endfor %}
            </div>


            <!----------------------- PAGINATION   ------------------->
            {% if is_paginated %}
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="/referral/list/?page={{ page_obj.previous_page_number }}"> < </a>
                            </li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active">
                                    <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="/referral/list/?page={{ page_obj.next_page_number }}"> > </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
{% endblock %}

referral/templates/update_of_referrals.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{#{% load crispy_forms_field %}#}
{#{% load crispy_forms_filters %}#}
{% block title %}
    Изменить реферала
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="page-header">
            <h3>Изменить реферала</h3>
            <a type="button" class="btn btn-primary" href="{% url 'referral:detail' object.slug %}">Назад</a>
        </div>
        <div class="custom-form">
            <form action="" method="post">{% csrf_token %}

                <br>

                {{ form.recruiter|as_crispy_field }}

                <br>

                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.middle_name|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.passport_id|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.slug|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.area|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.region|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.village|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.address|as_crispy_field }}
                    </div>
                </div>

                <br>

                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.birthday|as_crispy_field }}
                    </div>

                    <div class="form-group col-md-6 mb-0">
                        {{ form.status|as_crispy_field }}
                    </div>
                </div>

                <button class="btn btn-primary" type="submit">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock %}