home_page/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

referral/urls.py
from django.urls import path
from .views import *

app_name = 'referral'

urlpatterns = [
    path('create/', ReferralCreateView.as_view(), name='create'),
    path('list/', ReferralListView.as_view(), name='list'),
    path('detail/<slug:slug>/', ReferralDetailView.as_view(), name='detail'),
    path('update/<slug:slug>/', ReferralUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', ReferralDeleteView.as_view(), name='delete'),
    path('filter/<int:pk>', ReferralListView.referral_filter, name="filter"),

    # path('area/', ReferralArea.as_view(), name='area')
]

registration_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('referral/', include('referral.urls', namespace='referral')),
    path('recruiter/', include('recruiter.urls', namespace='recruiter')),
    path('user/', include('user.urls')),
    path('', include('home_page.urls', namespace='home')),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

home_page/models.py
from django.db import models

# Create your models here.

home_page/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import (LoginRequiredMixin)


class HomePageView(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'

home_page/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

</head>
<body>
{% if user.is_authenticated %}
    {% with url_name=request.resolver_match.view_name %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% if 'home' in url_name %}active{% endif %}">
                        <a class="nav-link" href="{% url 'home:home' %}">Главная<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item {% if 'recruiter' in url_name %}active{% endif %}">
                        <a class="nav-link" href="{% url 'recruiter:list' %}">Рекрутеры</a>
                    </li>
                    <li class="nav-item {% if 'referral' in  url_name %}active{% endif %}">
                        <a class="nav-link" href="{% url 'referral:list' %}">Рефералы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">Регионы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                    </li>
                </ul>

                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    {% endwith %}
{% endif %}


{% block content %}

{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

home_page/templates/home.html
{% extends 'base.html' %}
{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    <div class="page-container">
        <div class="home-page jumbotron">
            <!---------------- REFERRALS----->
            <a class="btn btn-primary btn-lg" href="{% url 'referral:create' %}" role="button">Создать реферала</a>
            <a class="btn btn-primary btn-lg" href="{% url 'referral:list' %}" role="button">Все рефералы</a>

            <!-------------- RECRUITERS----->
            <a class="btn btn-primary btn-lg" href="{% url 'recruiter:create' %}" role="button">Создать рекрутера</a>
            <a class="btn btn-primary btn-lg" href="{% url 'recruiter:list' %}" role="button">Все рекрутеры</a>
        </div>
    </div>
{% endblock %}